name: cofee
version: 4.0.0+62
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  auto_animated: ^3.1.0
  animated_digit: ^3.2.1
  async: any
  cached_network_image: ^3.2.3
  clipboard: ^0.1.3
  connectivity_plus: ^6.0.5
  contacts_service: ^0.6.3
  country_picker: ^2.0.19
  currency_formatter: ^2.0.0
  cupertino_icons: ^1.0.8
  dartz: 0.10.1
  device_preview: ^1.1.0
  dio: ^5.1.1
  dio_http2_adapter: ^2.2.0
  dropdown_button2: ^2.0.0
  firebase_crashlytics: ^4.1.1
  firebase_core: ^3.4.1
  firebase_messaging: ^15.1.1
  flutter:
    sdk: flutter
  flutter_custom_clippers: ^2.1.0
  flutter_displaymode: ^0.6.0
  flutter_dotenv: ^5.1.0
  flutter_layout_grid: ^2.0.7
  flutter_local_notifications: ^17.2.2
  flutter_native_splash: 2.4.1
  flutter_otp_text_field: ^1.1.1
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.0+1
  flutter_exif_rotation: ^0.5.1
  freezed: ^2.0.5
  freezed_annotation: ^2.2.0
  get: ^4.6.6
  get_it: ^7.7.0
  get_storage: ^2.1.1
  injectable: ^2.1.0
  package_info_plus: 8.1.4
  url_launcher: ^6.1.10
  intl: ^0.18.0
  json_annotation: ^4.7.0
  json_serializable: ^6.5.4
  flutter_keyboard_visibility: ^6.0.0
  logger: ^2.4.0
  mixpanel_flutter: 2.1.0
  oktoast: ^3.4.0
  on_screen_ruler: ^0.0.1
  path_provider: ^2.0.14
  percent_indicator: any
  permission_handler: ^11.3.1
  pinput: 5.0.0
  pixel_perfect: ^1.1.1
  pull_to_refresh: ^2.0.0
  scrollable_positioned_list: ^0.3.5
  smooth_page_indicator: ^1.0.0+2
  sms_autofill: ^2.2.0
  substring_highlight: ^1.0.33
  uuid: ^4.5.0
  image_picker: ^1.1.2
  skeletons:
    path: ./libraries/skeletons
  image_gallery_saver: ^2.0.3
  share_plus: ^10.0.2
  video_thumbnail: ^0.5.3
  app_links: ^6.3.2
  clear_all_notifications: ^1.0.0
  dotted_border: ^2.1.0
  image_cropper: 8.0.2
  http: ^1.2.2
  network_logger: ^1.0.4
  device_info_plus: ^10.1.2
  webview_flutter: ^4.5.0
  carousel_slider: ^5.0.0
  file_picker: 8.1.2
  circular_seek_bar: ^1.1.1
  timezone: ^0.9.3
  smart_auth: 2.0.0
  restart_app: ^1.2.1
  sentry_flutter: ^8.9.0
  flutter_branch_sdk: 8.2.0
  video_player: 2.9.2
  gif: 2.3.0
  flutter_slidable: ^3.1.1
  tutorial_coach_mark: ^1.2.12
  dlibphonenumber: ^1.1.29
  gradient_borders: ^1.0.1
  super_tooltip: ^2.0.9
  mobile_scanner: 6.0.5
  loading_animation_widget: ^1.3.0

dev_dependencies:
  build_runner: ^2.4.12
  flutter_gen_runner: null
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.3
  integration_test:
    sdk: flutter
  lints: ^4.0.0
  flutter_animate: any
  very_good_analysis: ^2.1.0
dependency_overrides:
  intl: ^0.18.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/videos/
    - .env
    - shorebird.yaml

  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans-Regular.ttf
        # - asset: fonts/DMSans-SemiBold.ttf
        - asset: assets/fonts/DMSans-Bold.ttf
        # - asset: fonts/DMSans-ExtraBold.ttf
        # - asset: fonts/DMSans-ExtraLight.ttf
        # - asset: fonts/DMSans-Light.ttf
        - asset: assets/fonts/DMSans-Italic.ttf
        - asset: assets/fonts/DMSans-Medium.ttf
