name: Create PR with CoFeeBot
on:
  workflow_dispatch:
    inputs:
      Branch:
        required: true
        type: choice
        description: Choose the target branch for PR
        options:
          - dev
          - stg
          - master
jobs:
  create-pr:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout feature branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git with Bot Identity
        run: |
          git config --global user.name "CoFeeBot"
          git config --global user.email "devopsadmin+cofee@keyvalue.systems"

      - name: Determine Target Branch
        id: target
        run: |
          echo "branch=${{ github.event.inputs.branch }}" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          TARGET_BRANCH=${{ steps.target.outputs.branch }}
          CURRENT_BRANCH=${{ github.ref_name }}

          # Check if PR already exists
          PR_EXISTS=$(gh pr list --head "$CURRENT_BRANCH" --base "$TARGET_BRANCH" --json number | jq length)

          if [ "$PR_EXISTS" -eq "0" ]; then
            gh pr create --base "$TARGET_BRANCH" --head "$CURRENT_BRANCH" \
              --title "Feature: Merge $CURRENT_BRANCH into $TARGET_BRANCH" \
              --body "This PR was automatically created by CoFeeBot."
            echo "Pull request created successfully"
          else
            echo "Pull request already exists, skipping creation"
          fi
